"""initial db models

Revision ID: 80dbe21e8059
Revises: 
Create Date: 2018-09-14 15:51:03.779139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80dbe21e8059'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('leadership', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('degree', sa.String(length=32), nullable=True),
    sa.Column('university', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workshop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_name', sa.String(length=64), nullable=True),
    sa.Column('workshop_category', sa.Enum('Academy', 'DSS', 'Corporate', 'Others', name='workshop_category'), nullable=False),
    sa.Column('workshop_instructor', sa.Integer(), nullable=False),
    sa.Column('workshop_start', sa.DateTime(), nullable=True),
    sa.Column('workshop_hours', sa.Integer(), nullable=True),
    sa.Column('workshop_venue', sa.String(length=64), nullable=True),
    sa.Column('class_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workshop_instructor'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assistants',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.id'], )
    )
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('assistants_score', sa.Integer(), nullable=True),
    sa.Column('knowledge', sa.Integer(), nullable=True),
    sa.Column('objectives', sa.Integer(), nullable=True),
    sa.Column('timeliness', sa.Integer(), nullable=True),
    sa.Column('venue_score', sa.Integer(), nullable=True),
    sa.Column('satisfaction_score', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    op.drop_table('assistants')
    op.drop_table('workshop')
    op.drop_table('employee')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
